use_frameworks!

platform :ios, '10.0'

target 'Rudder-GA4_Example' do
  pod 'Rudder-GA4', :path => '../'

  target 'Rudder-GA4_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
